In [6]:
import torch
import numpy as np
torch.__version__

'1.13.1'

Le travail avec les tensors de plusieurs dimension

In [5]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())
print(type(scalar.item()))
print(type(scalar))

tensor(7)
0
7
<class 'int'>
<class 'torch.Tensor'>


In [7]:
vector = torch.tensor([1,2])
print(vector)
print(vector.shape)

tensor([1, 2])
torch.Size([2])


In [15]:
rand_t = torch.rand(size=(1,2,3))
rand_t = torch.rand(2,1,1)
print(rand_t, rand_t.dtype)

tensor([[[0.8237]],

        [[0.4465]]]) torch.float32


In [17]:
zeros = torch.zeros(1,1,1)
ones = torch.ones(3,2,1)
print(zeros, ones)

tensor([[[0.]]]) tensor([[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]])


In [22]:
a = torch.arange(1,10,2)
print(a)
zeros_as = torch.zeros_like(a)
print(zeros_as)

tensor([1, 3, 5, 7, 9])
tensor([0, 0, 0, 0, 0])


In [28]:
tensor = torch.tensor([3,1.0,3],
                      dtype=None,
                      device=None,
                      requires_grad=False)
    
print(tensor.shape, tensor.dtype, tensor.device)


torch.Size([3]) torch.float32 cpu


In [27]:
tensor *= 10
tensor += 10
tensor

tensor([6010., 2010., 6010.])

In [44]:
torch.manual_seed(14)
linear = torch.nn.Linear(in_features=3,
                         out_features=5)



x =tensor 
output = linear(x)
print(output)
print(output.max())
print(output.min())
print(output.argmin())
print(output.argmin)
print(torch.argmin(output))

tensor([ 0.8298,  1.5551, -2.0902,  1.0008, -0.3074], grad_fn=<AddBackward0>)
tensor(1.5551, grad_fn=<MaxBackward1>)
tensor(-2.0902, grad_fn=<MinBackward1>)
tensor(2)
<built-in method argmin of Tensor object at 0x7f8a9013ef40>
tensor(2)


In [49]:
import numpy as np 
arr = np.arange(1, 8)
tens = torch.from_numpy(arr)
print(arr, tens)
tens = tens.numpy()
print(tens)

[1 2 3 4 5 6 7] tensor([1, 2, 3, 4, 5, 6, 7])
[1 2 3 4 5 6 7]


In [46]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [48]:
torch.cuda.is_available()


False